modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/Mrbysco/measurements/issues"
license="MIT"

[[mods]]
modId="measurements"
version="${file.jarVersion}"
displayName="Measurements"
displayURL="https://www.curseforge.com/minecraft/mc-mods/measurements"
authors="Mrbysco"
description='''
Measure the distance between positions :)
'''
[[dependencies.measurements]]
modId="forge"
mandatory=true
versionRange="[44.1.0,)"
ordering="NONE"
side="BOTH"