modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/Mrbysco/measurements"
license="MIT"

[[mods]]
modId="measurements"
version="${file.jarVersion}"
displayName="Measurements"
displayURL="https://www.curseforge.com/minecraft/mc-mods/measurements"
authors="Mrbysco"
description='''
Measure the distance between positions :)
'''
[[dependencies.measurements]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,1.20)"
ordering="NONE"
side="BOTH"