modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/measurements"
license="MIT"

[[mods]]
modId="measurements"
version="${file.jarVersion}"
displayName="Measurements"
displayURL="https://www.curseforge.com/minecraft/mc-mods/measurements"
authors="Mrbysco"
description='''
Measure the distance between positions :)
'''