modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/measurements/issues"
license="MIT"

[[mods]]
modId="measurements"
version="${file.jarVersion}"
displayName="Measurements"
displayURL="https://www.curseforge.com/minecraft/mc-mods/measurements"
authors="Mrbysco"
description='''
Measure the distance between positions :)
'''
[[dependencies.measurements]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.measurements]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.117-beta,)"
ordering="NONE"
side="BOTH"